#!/usr/bin/python
import boto
import boto.cloudformation
import argparse

with open ("basic.template", "r") as myfile:
    template=myfile.read()

cfn = boto.cloudformation.connect_to_region('us-west-2')
stack_name = "testStack55"
t_url = "https://s3.amazonaws.com/cloudformation-samples-us-east-1/LAMP_Simple.template"
cfn.create_stack(stack_name, template_body=template,capabilities=['CAPABILITY_IAM']) 

print "Listing Stacks"
stacks = cfn.list_stacks()
for stack in stacks:
    print stack.stack_id, stack.stack_status

