#!/usr/bin/python
import boto.ec2

region = 'us-west-2'
AMI_ID = 'ami-6aad335a'
INSTANCE_TYPE = 't1.micro'
EC2_KEY_HANDLE = 'Default'
SECGROUP_HANDLE = 'default'

conn = boto.ec2.connect_to_region(region)
reservation = conn.run_instances( image_id=AMI_ID, 
                                 key_name=EC2_KEY_HANDLE, 
                                 instance_type=INSTANCE_TYPE,
                                 security_groups = [ SECGROUP_HANDLE, ] )

