#!/usr/bin/python
import boto
import boto.cloudformation
import argparse

with open ("basic.template", "r") as myfile:
    template=myfile.read()

cfn = boto.cloudformation.connect_to_region('us-east-1')
stack_name = "testStack55"
t_url = "https://beh_cf.s3.amazonaws.com/gluster"
cfn.create_stack(stack_name, template_body=template) 

print "Listing Stacks"
stacks = cfn.list_stacks()
for stack in stacks:
    print stack.stack_id, stack.stack_status

